package window;

import solution.Data;
import solution.Solution;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author misha
 */
public class Graph extends javax.swing.JFrame {
    private int countOfGraph = 0;
    private final XYSeriesCollection xysc = new XYSeriesCollection();
    private boolean isFirstGraph = true;

    public void addGraph(
            double[] X, double[] Y, String name) {
        XYSeries series = new XYSeries(name);
        for (int i = 0; i < X.length; i++)
            series.add(X[i], Y[i]);
        xysc.addSeries(series);
    }

    public void clear() {
        xysc.removeAllSeries();
        countOfGraph = 0;
    }

    public void building(String nameMethods) {
        JFreeChart chart = ChartFactory.createXYLineChart(
                nameMethods, "\u03B8", "u",
                xysc,
                PlotOrientation.VERTICAL,
                true, true, true);
        drawPanel.setLayout(new java.awt.BorderLayout());
        drawPanel.add(new ChartPanel(chart));
        drawPanel.validate();
        drawPanel.updateUI();
    }

    /**
     * Creates new form Graph
     */
    public Graph() {
        initComponents();
        startButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                startButtonActionPerformed(actionEvent);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        cTextField = new javax.swing.JTextField();
        cFormattedTextField = new javax.swing.JFormattedTextField();
        kFormattedTextField = new javax.swing.JFormattedTextField();
        rFormattedTextField = new javax.swing.JFormattedTextField();
        betaFormattedTextField = new javax.swing.JFormattedTextField();
        epsFormattedTextField = new javax.swing.JFormattedTextField();
        startButton = new javax.swing.JButton();
        rTextField = new javax.swing.JTextField();
        KTextField = new javax.swing.JTextField();
        epsTextField = new javax.swing.JTextField();
        betaTextField = new javax.swing.JTextField();
        drawPanel = new javax.swing.JPanel();
        tTextField = new javax.swing.JTextField();
        tFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("basicFrame"); // NOI18N

        cTextField.setEditable(false);
        cTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cTextField.setText("c");

        cFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFormattedTextFieldActionPerformed(evt);
            }
        });
        cFormattedTextField.setText("2.0");

        kFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kFormattedTextFieldActionPerformed(evt);
            }
        });
        kFormattedTextField.setText("0.01");

        rFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFormattedTextFieldActionPerformed(evt);
            }
        });
        rFormattedTextField.setText("2.0");

        betaFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        betaFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaFormattedTextFieldActionPerformed(evt);
            }
        });
        betaFormattedTextField.setText("0.1");

        epsFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        epsFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsFormattedTextFieldActionPerformed(evt);
            }
        });
        epsFormattedTextField.setText("1e-7");

        startButton.setText("start");

        rTextField.setEditable(false);
        rTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rTextField.setText("R");

        KTextField.setEditable(false);
        KTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KTextField.setText("K");

        epsTextField.setEditable(false);
        epsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        epsTextField.setText("\u03B5");

        betaTextField.setEditable(false);
        betaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        betaTextField.setText("\u03B2");

        tTextField.setEditable(false);
        tTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tTextField.setText("t");

        tFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFormattedTextFieldActionPerformed(evt);
            }
        });
        tFormattedTextField.setText("0.001");

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
                drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 506, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
                drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(epsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(epsFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(betaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(rTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(KTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(kFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(kFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(KTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(rTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(betaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(epsFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(epsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(startButton))
                                        .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void cFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void betaFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void epsFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Data.beta_$eq(Double.parseDouble(betaFormattedTextField.getText()));
        Data.c_$eq(Double.parseDouble(cFormattedTextField.getText()));
        Data.eps_$eq(Double.parseDouble(epsFormattedTextField.getText()));
        Data.K_$eq(Double.parseDouble(kFormattedTextField.getText()));
        Data.R_$eq(Double.parseDouble(rFormattedTextField.getText()));
        Data.t_$eq(Double.parseDouble(tFormattedTextField.getText()));
        if (isFirstGraph) {
            Data.init();
        }
        double[] X = new double[100];
        double[] Y = new double[100];
        double value = Math.PI * 0.01;
        int i = 0;
        double t = Data.t();
        java.text.DecimalFormat f3 = new java.text.DecimalFormat("0.000");
        for (double x = 0.0; i < 100; x += value, i += 1) {
            X[i] = x;
            Y[i] = Solution.u(t, x);
        }
        addGraph(X, Y, "u" + ((countOfGraph == 0) ? "" : countOfGraph) +
                "(" + f3.format(t) + "; θ)");
        countOfGraph++;
        if (isFirstGraph) {
            isFirstGraph = false;
            building("Graph of function u(t,θ)");
        }
    }

    private void startButtonMouseClicked(java.awt.event.ActionEvent evt) {
        startButtonActionPerformed(evt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField KTextField;
    private javax.swing.JFormattedTextField betaFormattedTextField;
    private javax.swing.JTextField betaTextField;
    private javax.swing.JFormattedTextField cFormattedTextField;
    private javax.swing.JTextField cTextField;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JFormattedTextField epsFormattedTextField;
    private javax.swing.JTextField epsTextField;
    private javax.swing.JFormattedTextField kFormattedTextField;
    private javax.swing.JFormattedTextField rFormattedTextField;
    private javax.swing.JTextField rTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JFormattedTextField tFormattedTextField;
    private javax.swing.JTextField tTextField;
    // End of variables declaration
}
